### ISSUE TITLE
[iOS]: "RNTfliteSpec.h" not found in RN 0.75 with new arch

### ISSUE THREAD

**Issue by mbpictures** [mrousavy/react-native-fast-tflite#87]
Hi!

I'm using react-native 0.75 with the new architecture enabled and I'm getting an XCode compile error, that the file "RNTfliteSpec.h" could not be found in [this](https://github.com/mrousavy/react-native-fast-tflite/blob/1d73f8a7abc762ec946275e2c71ec2e1c9315ccc/ios/Tflite.h#L3) line:
```
#import "RNTfliteSpec.h"
```

There was an issue regarding this problem but it has been closed without solving, so I'm creating a new one. Any help in addressing this problem would be highly appreciated! Thanks already!

**Comment by lucksp** [comment]
I am seeing this also, however, I am still on RN `0.73.6` with RNVC `4.5.1` and RNFastTFLite `1.3.0`.

- expo : ~50.0.19
 - react : 18.2.0
 - react-native : 0.73.6
I get this error building for Android.  Here is the error output:

```

```

**Comment by liontariai** [comment]
I think this happens, because there's no `codegenConfig` in the package.json for `@react-native/codegen` to generate the turbomodule header file. 

https://github.com/mrousavy/react-native-fast-tflite/issues/14#issuecomment-1903497131

@mrousavy as you mentioned here, the file is missing, correct. But it's not that you would create it by hand. It seems it would be generated, if the config is set up properly. I found a tutorial here: https://medium.com/@sanchitsrivastava247/creating-turbo-module-in-react-native-0-74-73c6cae6a945

I'll try to fix this somehow and report back. Perhaps we can come up with a PR

**Comment by liontariai** [comment]
You can try my fork: https://github.com/liontariai/react-native-fast-tflite

1) Install from github with `"react-native-fast-tflite": "liontariai/react-native-fast-tflite",`
2) Copy the dir `https://github.com/liontariai/react-native-fast-tflite/tree/main/src/expo-plugin` into your root project
3) In `withFastTFLite.ts` replace `const pkg = require('../../../package.json')` with `const pkg = require("react-native-fast-tflite/package.json");`
4) Use the plugin from your root project in your expo config. The reason for this is, that otherwise you'd be importing Typescript from a node_modules location which doesn't work. The correct fix for this would be to publish an updated package, but this is WIP.

**Comment by lucksp** [comment]
> but my build is failing just because I have "react-native-fast-tflite" installed

What is the build failure message?

**Comment by mSenad** [comment]
@lucksp Thanks for hopping in.

So, currently I uninstall 'react-native-fast-tflite' and tried to build my app and everything works as expected.

**When I:**
- install react-native-fast-tflite
- cd ios/
- pod install ( which shows me : Installing TensorFlowLiteC (2.17.0) Installing react-native-fast-tflite (1.5.0 )

This is everything I do, than I go to build my app from the xcode and here is the error:

<img width="1385" alt="Screenshot 2024-11-12 at 4 23 52 PM" src="https://github.com/user-attachments/assets/be844583-9842-4192-bf90-e4f9033e3e5b">

**Comment by liontariai** [comment]
Hey @mSenad , I'll try my best:

I think generally you need to do the exact same thing I did, the error you see is what I saw.
The problem is that the package is not fully implemented as TurboModule, which is required (?) for the new architecture.

So if you follow the steps I have outlined above, you should be able to fix it. The only thing that's different, is that you'll be doing the things that are done by the expo plugins manually.

If I see it right, the plugin only adds a variable to your Podfile and adds a Framework to the XCode project:
![grafik](https://github.com/user-attachments/assets/cbf94eae-1520-4e59-83fe-1f9b651ad2ea)

And this is also only done, if you want to use the CoreML Delegates (i'm no expert on what it is / why you'd need it... i think it's like GPU/NeuralEngine acceleration?)
![grafik](https://github.com/user-attachments/assets/44d35142-9ca6-46db-aa78-60a01a1f36bb)


So therefore, you might as well skip the expo plugins / Podfile modifications and might still work...
Give it a try and report back, so I might help you further if needed ;)

**Comment by mSenad** [comment]
@liontariai thanks man, I really appreciate it that you took your time to give me some insights.

Currently, when I run `npm install liontariai/react-native-fast-tflite` my terminal just stucks. Is there something that I need to do here in order to have this package installed or?

...and how I understood, I just need to have `expo-plugin` folder in my project root level and apply the changes you've mentioned, right?

**Comment by liontariai** [comment]
you're welcome! Well... I'm not 100% sure why it stucks. I have installed it by putting it in my package.json and running the install then, I'm not sure how you tell npm to look at github via the cli command, even though it might be correct the way you did it.

![grafik](https://github.com/user-attachments/assets/0aae692f-0d62-415c-9244-49ceff5e49a9)

Also you could check if you have some logs for npm. I think it prints logs somewhere in the /tmp dir.
Could be that there's some post-install script running a `pod install` maybe? I'm not sure but if I remember correctly, the pod install can take some time...

Regarding the plugins... if you don't use expo, you shouldn't need to do anything other than installing the package from my repo.

**Comment by liontariai** [comment]
Yes, you can definitely do that.
You can try your own fork, or for the time being just apply the changes in your locally installed pkg.
I only made a fork so that it would be somewhat consistent and not vanish after a fresh install of packages... and also to have a starting point to make a contribution back to this package.

**Comment by fwcd** [comment]
Disabling the new arch fixed it for me too. I had to use

```sh
RCT_NEW_ARCH_ENABLED=0 pod install
```

to reinstall/regenerate the CocoaPods project.

**Comment by gpbaculio** [comment]
Is there workaround atm for with new Arch?

**Comment by liontariai** [comment]
> Is there workaround atm for with new Arch?

https://github.com/mrousavy/react-native-fast-tflite/issues/87#issuecomment-2450366198

try my guide

**Comment by lucksp** [comment]
> done, if you want to use the CoreML Delegates (i'm no expert on what it is / why you'd need it... i think it's like GPU/NeuralEngine acceleration?)

Does any one else have issues with iOS GPU on packages 1.40 and up?  It’s fine on 1.3.0

**Comment by boorad** [comment]
> You can try my fork: https://github.com/liontariai/react-native-fast-tflite

@liontariai I also have a fork now, updated for fast-tflite recent commits since yours.  You should open a PR to get yours merged in, as I don't think there are any conflicts.  It may only be a stop-gap until it can all use Nitro, but still, we should discuss it in a PR 🙂

**Comment by liontariai** [comment]
> > You can try my fork: https://github.com/liontariai/react-native-fast-tflite
> 
> @liontariai I also have a fork now, updated for fast-tflite recent commits since yours. You should open a PR to get yours merged in, as I don't think there are any conflicts. It may only be a stop-gap until it can all use Nitro, but still, we should discuss it in a PR 🙂

yes you're right... haven't really worked on the project I needed this for since then, but I'll open a PR as soon as I get back to it 👍

**Comment by rmscrlos** [comment]
I tried implementing the workaround but I can't no longer `npm i`. Doing this step 1 where you just past `"react-native-fast-tflite": "liontariai/react-native-fast-tflite"` in the package.json breaks it for me.

```
npm error code 128
npm error git dep preparation failed
npm error command /Users/carlosramos/.nvm/versions/node/v22.11.0/bin/node /Users/carlosramos/.nvm/versions/node/v22.11.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/carlosramos/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm error > react-native-fast-tflite@1.4.0 prepare
npm error > git submodule update --init --recursive
npm error npm warn using --force Recommended protections disabled.
npm error npm warn deprecated @types/react-native@0.73.0: This is a stub types definition. react-native provides its own type definitions, so you do not need this installed.
npm error npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm error npm warn deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm error npm warn deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm error npm warn deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm error npm warn deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm error npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm error npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm error npm warn deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm error npm warn deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm error npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm error npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm error npm warn deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm error npm warn deprecated sudo-prompt@9.2.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm error npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
npm error npm warn deprecated @humanwhocodes/object-schema@2.0.2: Use @eslint/object-schema instead
npm error npm warn deprecated @xmldom/xmldom@0.7.13: this version is no longer supported, please update to at least 0.8.*
npm error npm warn deprecated eslint@8.56.0: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm error fatal: not a git repository (or any of the parent directories): .git
npm error npm error code 128
npm error npm error path /Users/carlosramos/.npm/_cacache/tmp/git-clonebXTygH
npm error npm error command failed
npm error npm error command sh -c git submodule update --init --recursive
npm error npm error A complete log of this run can be found in: /Users/carlosramos/.npm/_logs/2025-01-19T05_25_18_505Z-debug-0.log
npm error A complete log of this run can be found in: /Users/carlosramos/.npm/_logs/2025-01-19T05_24_22_660Z-debug-0.log
```

**Comment by Jonatthu** [comment]
I guess this is stuck? This is happening to me on expo newest version and RN 0.76

**Comment by boorad** [comment]
There are [two](https://github.com/liontariai/react-native-fast-tflite) [forks](https://github.com/boorad/react-native-fast-tflite) you can point your package.json to in the comments above.  Maybe @liontariai will submit the PR... he did the work 😉

**Comment by Jonatthu** [comment]
@boorad why did you delete the pull request?

**Comment by Jonatthu** [comment]
@mrousavy are we merging this?

**Comment by mrousavy** [comment]
merged

**Comment by justrustc** [comment]
@mrousavy When will the new version be released?

**Comment by iradcn** [comment]
Hey @liontariai thanks for contributing the fix!
Until the version is released, I'm using your fix.
Would you please elaborate on how to accomplish your step 4:

> Use the plugin from your root project in your expo config. The reason for this is, that otherwise you'd be importing Typescript from a node_modules location which doesn't work. The correct fix for this would be to publish an updated package, but this is WIP.

Thanks!

**Comment by liontariai** [comment]
> Hey [@liontariai](https://github.com/liontariai) thanks for contributing the fix! Until the version is released, I'm using your fix. Would you please elaborate on how to accomplish your step 4:
> 
> > Use the plugin from your root project in your expo config. The reason for this is, that otherwise you'd be importing Typescript from a node_modules location which doesn't work. The correct fix for this would be to publish an updated package, but this is WIP.
> 
> Thanks!

Here you go:

Basically Step 2 - 4 results in the following setup:

You have the expo plugin in your own code and adjust an import (require) statement and then use that in your expo plugins directly.

![Image](https://github.com/user-attachments/assets/d5cac1fb-a099-4a2a-93e8-8c106e7e8abf)

![Image](https://github.com/user-attachments/assets/3dc49a1d-6ffe-41a4-a05f-34ee9c9de38f)

**Comment by mrousavy** [comment]
Released in [1.6.0](https://github.com/mrousavy/react-native-fast-tflite/releases/tag/v1.6.0)! :)

**Comment by shehanGuruge** [comment]
Hi,

I am still getting this issue.

```
/ios/Tflite.h:3:9: 'RNTfliteSpec.h' file not found

#import "RNTfliteSpec.h"
```

I also got this issue previously when trying to install pods 
https://github.com/mrousavy/react-native-fast-tflite/issues/133

and i fixed it in my local environment with below changes
```
  "codegenConfig": {
    "name": "NativeRNTflite",
    "type": "modules",
    "jsSrcsDir": "lib/spec"
  },
```

Afterwards I keep getting the  `'RNTfliteSpec.h' file not found in.`

This is my package.json

```
  "dependencies": {
    "react": "19.0.0",
    "react-native": "0.78.1",
    "react-native-fast-tflite": "^1.6.0",
    "react-native-vision-camera": "^4.6.4"
  },
```

How to fix this issue?

**Comment by jslok** [comment]
Getting an error trying to build with new arch on 0.75.5. No expo, which maybe the difference here? Will try to debug some more.

```
/Users/**/**/node_modules/react-native-fast-tflite/ios/Tflite.h:4:33 Cannot find protocol declaration for 'NativeTfliteSpec'; did you mean 'NativeRNTfliteSpec'?
```

```
/Users/**/**/node_modules/react-native-fast-tflite/ios/Tflite.mm:58:46 No member named 'NativeTfliteSpecJSI' in namespace 'facebook::react'

```

**Comment by lucksp** [comment]
> Getting an error trying to build with new arch on 0.75.5. No expo, which maybe the difference here? Will try to debug some more.
> 
> ```
> /Users/**/**/node_modules/react-native-fast-tflite/ios/Tflite.h:4:33 Cannot find protocol declaration for 'NativeTfliteSpec'; did you mean 'NativeRNTfliteSpec'?
> ```
> 
> ```
> /Users/**/**/node_modules/react-native-fast-tflite/ios/Tflite.mm:58:46 No member named 'NativeTfliteSpecJSI' in namespace 'facebook::react'
> ```

this lib is only in maintenance mode...
