### ISSUE TITLE
Please release the updated library

### ISSUE THREAD

**Issue by DZamataev** [mrousavy/react-native-fast-tflite#88]
After merging [this PR](https://github.com/mrousavy/react-native-fast-tflite/pull/85) the library runs fine on iOS Simulator. But the library cannot be easily pulled in any react-native application package.json directly from main like so 
```
    "react-native-fast-tflite": "mrousavy/react-native-fast-tflite#main",
```
because the tensorflow submodule appears empty in node_modules/react-native-fast-tflite/tensorflow.

Thats why I kindly ask @mrousavy to release the updated version of the library (1.3.1). For the users to be able to use it in their react-native projects without suffering the inability to run on iOS Simulator. Thank you in advance!

**Comment by mrousavy** [comment]
released 1.4.0 👍

**Comment by Pingou** [comment]
@mrousavy doesn't seem to compile now, any one else is having the same issue?

https://github.com/mrousavy/react-native-fast-tflite/issues/91

**Comment by Mateo-Abribat** [comment]
Doesn't work on Android in 1.4.0 ! But it works on IOS 😭

**Comment by Mateo-Abribat** [comment]
Here is the error:
node_modules/react-native-fast-tflite/android/../cpp/TensorflowPlugin.h:19:10: fatal error: 'tensorflow/lite/c/c_api.h' file not found
  #include <tensorflow/lite/c/c_api.h>
@mrousavy

**Comment by manu13008** [comment]
Same issue here ! Anyone knows how to fix it without cloning all the tensorflow repository into the react native tflite fast module each time ?

**Comment by Pingou** [comment]
@manu13008 have you tried pointing to master in instead of the npm version?
Ex of package.json:  "react-native-fast-tflite": "git://github.com/mrousavy/react-native-fast-tflite#master",

**Comment by manu13008** [comment]
Okay. So nothing worked for me on Windows :( I still get the same error as previous

**Comment by lucksp** [comment]
1.4.0 builds on iOS simulator, but I am seeing #91 errors in Android
